### PR TITLE
Update to zfs version 2.2.7

### PR DESCRIPTION
**Pull request by nightah**
# Supported Platforms

* Linux: compatible with 4.18 - 6.12 kernels

### CODE REVIEW

**Review by l-vanni — APPROVED** [review]
ZFS version and SHA256 are correct. All build checks are passed. Thanks for PR!

**Review by Doridian — APPROVED** [review]

**Comment by minextu** [comment]
I'm thinking we merge this and https://github.com/archzfs/archzfs/pull/564, then trigger a new build on the old buildbot system to push out a release there too

**Comment by l-vanni** [comment]
@Doridian can you merge this PR? 
Many thanks

**Comment by alkeryn** [comment]
damn, i can update my arch kernel after like 4+ months i don't even remember when was the last time lmao.

**Pull request merged**
