### PR TITLE
Update to ZFS v2.1.9, follow upstream branding

### PR DESCRIPTION
**Pull request by forkbomb9**
ZFSonLinux has been OpenZFS for a while now. If these changes aren't welcome, or I need to fix something with the OpenZFS branding, please let me know.

### CODE REVIEW

**Comment by minextu** [comment]
Thank you! Right now this is blocked by https://github.com/archzfs/archzfs/issues/475, I will take a look and merge it as soon as this is resolved

**Comment by eirnym** [comment]
@minextu how release package is blocked by git version?

**Comment by minextu** [comment]
> @minextu how release package is blocked by git version?

I was assuming this would happen to new utils packages in general, turned out to be not the case though

**Comment by eirnym** [comment]
I understand. Thank you

**Pull request merged**
