### PR TITLE
Fix dependency for a fixed common-utils version (git packages)

### PR DESCRIPTION
**Pull request by minextu**
Part 2 of https://github.com/archzfs/archzfs/pull/189
Totally forgot about the git packages last time, sorry

### CODE REVIEW

**Comment by minextu** [comment]
Since we have a `pkgver()` function we get another problem by merging this: AUR users will only be able to build the package as long as no new commit as been added to zfs.
When pkgver() updates the version, the version of  the common-git dependency doesn't update automatically with it...

Maybe it would be better to not merge this. With the addition of an `all` command, out of sync packages might not happen anymore and aur users could still build the packages without modifying the pkgbuild

**Comment by demizer** [comment]
Another thing we could do is lock the git checkout to a specific commit for people building from AUR. This commit target is updated with automation if we rebuild the git packages using the all or common-git modes of build.sh, which happens often. This way users can build git packages from aur without breakage. This also makes it so when we run tests against the git packages, we know for sure the checkout works.

**Comment by demizer** [comment]
We do something similar at https://github.com/archzfs/archzfs/blob/master/build.sh#L303

**Comment by minextu** [comment]
I added new commits to implement that

**Comment by demizer** [comment]
Thank you!

**Pull request merged**
